### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by mkh63d** [alexbud1/tul-programming-technologies#7]
# Task 2 Check list

- [x] text is in C# and use .NET
- [ ] build succeeded
- [ ] all UT are green
- [x] Object model representing process data (reuse it from Task1)
- [x] layers are clearly stated in the language terms
- [x] `Data` layer is implemented using external SQL database and should be defined using LINQ to SQL (ORM)
- [x] LINQ (method and query syntax) is used to fetch data from the database
- [x] `Presentation` - his layer must be implemented in accordance with the `Model-View-ViewModel` (`MVVM`) software pattern
- [x] `Presentation` - the Master-Detail pattern
- [ ] `View Model` must be tested using 2 independent `Model` data generation methods
- [ ] `View Model` is tested independently
- [ ] `View Model` use dependency injection for testing purpose (additional framework is not required)
- [ ] The data and controls must be bond together using the data binding mechanism
- [x] `View` - design the appropriate GUI using `XAML` language (it should be C# codeless)

**Comment by mkh63d** [comment]
- [x] tests should be forked based on which layer they refer to
- [x] implementations should be internal
- [ ] code should not use id's, but references 
- [ ] Add dictionaries

**Comment by mkh63d** [comment]
@alexbud1 so as u may see i marked already several changes, I hope they are before any yours changes so that any namespaces won't collapse, and u wouldn't need solve any merge conflicts
